Setup
Mwapsam/portifolio pull request #1
Opened 2021-11-24 21:01 UTC by Mwapsam

- Add index.html
- Add main.css
- Add linters config
- Add readme

2021-11-24 22:05 UTC, alonsofl requested changes
Hi @Mwapsam,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] I would suggest updating your README to make your repository more professional. You could use this [README template](https://github.com/microverseinc/readme-template) and customize it with your project's information. Remember that this file is the first thing recruiters and team members will see when checking your project :pushpin: :wink:

_Check the comments under the review._

## To highlight :dart:
- Linters working properly :heavy_check_mark:
- Well documented PR description :heavy_check_mark:
- Commit messages are meaningful :heavy_check_mark:
- Good HTML structure :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing the first letter of your commit messages :pushpin:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 22:05 UTC, alonsofalconi commented on index.html
> +        </nav>
- [ ] You have done an excellent job with your project :muscle: but I would suggest moving your `<h2>` tag outside of the `<nav>` tag and also this should be an `<a>` tag because the common convention is that the "logo" (in your situation "SMC") it's a link to the index page :wink:

2021-11-24 22:05 UTC, alonsofalconi commented on index.html
> +                </ul>
- [ ] [OPTIONAL] This is a great use of the `<ul>` tag to list items :clap: and it could be a good idea to add the correct links to your socials :smiley:

2021-11-24 22:05 UTC, alonsofalconi commented on main.css
> +  background-position: center;
- [ ] There is an issue with your background image because it shows empty blank spaces to the sides. Could you fix it to make your portfolio look even better :raised_hands:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/143316669-a9d19ce4-21b9-4377-92de-8fcc550640de.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/143316700-6f6729c6-9903-4522-9c85-b789283d3e87.png)

- [ ] I think your design has some layout/spacing issues in order to match the Figma design because the headline text is too close to the toolbar and there should be more space. Please, fix these layout/spacing issues to match the Figma design :raised_hands:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/143317320-1d336f6c-4c83-4a6c-ab0c-afd80cb84eeb.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/143317359-f29ac785-0d5d-4bca-acd8-fb5c350c807a.png)

2021-11-24 22:05 UTC, alonsofalconi commented on index.html
> +                <h1 class="icons-text">LET’S CONNECT</h1>
- [x] I would suggest using the `<p>` tag instead of the `<h1>`. Remember that there could only be one `<h1>` per page and this text could be considered a common paragraph :wink:
**I think that change will also fix the font-weight because the Figma design is 400 (normal)**

2021-11-25 10:18 UTC, keneogu requested changes
Hi @Mwapsam , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------

2021-11-25 10:18 UTC, keneogu commented on index.html
> +        </nav>
- [ ] Your `<h2>` tag is supposed to be a logo. If you notice most websites, the logo is usually a link so you can go back to the home page or index page by clicking it. You can make it a link by using the `<a>` tag. Also, move it outside the `<nav>` tag.

2021-11-25 11:37 UTC, mmsesay approved these changes
Hi @Mwapsam , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 11:56 UTC, merged